ENT.Type        = "anim" -- Данное творение принадлежит проекту [.ambition]
ENT.Base        = "base_gmodentity" -- Данное творение принадлежит проекту [.ambition]
ENT.PrintName   = "Камень" -- Данное творение принадлежит проекту [.ambition]
ENT.Author      = "[.ambition]" -- Данное творение принадлежит проекту [.ambition]
ENT.Category    = "[.ambition] Шахта и балалайка" -- Данное творение принадлежит проекту [.ambition]
ENT.Spawnable   = true -- Данное творение принадлежит проекту [.ambition]
