Ambi.Rus.restrict_items[ 'Cars' ] = {
    [ 'Seat_Airboat' ] = { level = 1, delay = 1, max = 8 },
    [ 'Chair_Office2' ] = { level = 1, delay = 1, max = 8 },
    [ 'phx_seat' ] = { level = 1, delay = 1, max = 8 },
    [ 'phx_seat2' ] = { level = 1, delay = 1, max = 8 },
    [ 'phx_seat3' ] = { level = 1, delay = 1, max = 8 },
    [ 'Chair_Plastic' ] = { level = 1, delay = 1, max = 8 },
    [ 'Seat_Jeep' ] = { level = 1, delay = 1, max = 8 },
    [ 'Chair_Office1' ] = { level = 1, delay = 1, max = 8 },
    [ 'Chair_Wood' ] = { level = 1, delay = 1, max = 8 },

    ----------------------------------------------------------------------------
    [ 'Airboat' ] = { level = 2, delay = 20, max = 2 },
    [ 'Jeep' ] = { level = 2, delay = 20, max = 2 },
    [ 'Pod' ] = { level = 2, delay = 20, max = 2 },

    ----------------------------------------------------------------------------
    [ 'eraz762srd' ] = { level = 2, delay = 20, max = 2 },
    [ 'fordvic1srd' ] = { level = 2, delay = 20, max = 2 },
    [ 'gazchaikasrd' ] = { level = 2, delay = 20, max = 2 },
    [ 'gaz21srd' ] = { level = 2, delay = 20, max = 2 },
    [ 'gaz2410copsrd' ] = { level = 2, delay = 20, max = 2 },
    [ 'izh412srd' ] = { level = 2, delay = 20, max = 2 },
    [ 'raf22031ambusrd' ] = { level = 2, delay = 20, max = 2 },
    [ 'renaultlogansrd' ] = { level = 2, delay = 20, max = 2 },
    [ 'uaz1912banksrd' ] = { level = 2, delay = 20, max = 2 },
    [ 'vaz2106taxsrd' ] = { level = 2, delay = 20, max = 2 },
    [ 'zil133540srd' ] = { level = 2, delay = 20, max = 2 },
    [ 'zil5423srd' ] = { level = 2, delay = 20, max = 2 },

    ----------------------------------------------------------------------------
    [ 'sim_fphys_couch' ] = { level = 2, delay = 10, max = 2 },
    [ 'sim_fphys_dukes' ] = { level = 2, delay = 10, max = 2 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_blistac' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_bravura' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_buccanee' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_cadrona' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_clover' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_club' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_esperant' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_feltzer' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_fortune' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_hermes' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_hustler' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_majestic' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_manana' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_previon' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_sabre' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_stallion' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_tampa' ] = { level = 3, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_virgo' ] = { level = 3, delay = 10, max = 10 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_ambulan' ]  = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_barracks' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_enforcer' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_fbiranch' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_fbitruck' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_firetruk' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_firela' ]   = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_copcarla' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_copcarvg' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_copcarsf' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_copcarru' ] = { level = 4, delay = 10, max = 10 },
    [ 'simfphys_gta_sa_swatvan' ]  = { level = 4, delay = 10, max = 10 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_benson' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_boxville' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_cement' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_combine' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_dft30' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_dozer' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_dumper' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_flatbed' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_forklift' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_linerun' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_mule' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_packer' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_rdtrain' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_petro' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_tractor' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_yankee' ] = { level = 4, delay = 20, max = 10 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_blade' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_broadway' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_remingtn' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_savanna' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_slamvan' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_tahoma' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_tornado' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_voodoo' ] = { level = 3, delay = 20, max = 10 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_bloodra' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_bloodrb' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_hotring' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_hotrina' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_hotrinb' ] = { level = 4, delay = 20, max = 10 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_bandito' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_bfinject' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_caddy' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_camper' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_duneride' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_journey' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_kart' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_mower' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_quad' ] = { level = 4, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_vortex' ] = { level = 4, delay = 20, max = 10 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_baggage' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_bus' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_cabbie' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_coach' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_sweeper' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_taxi' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_towtruck' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_towtruck' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_tug' ] = { level = 3, delay = 20, max = 10 },
    [ 'simfphys_gta_sa_utility' ] = { level = 3, delay = 20, max = 10 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_bobcat' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_huntley' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_landstalker' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_mesa' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_monster' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_monstera' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_monsterb' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_patriot' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_picador' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_rancher' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_sadler' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_sadlshit' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_sandking' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_walton' ] = { level = 5, delay = 10, max = 15 },
    [ 'simfphys_gta_sa_yosemite' ] = { level = 5, delay = 10, max = 15 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_admiral' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_elegant' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_emperor' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_glendale' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_glenshit' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_greenwoo' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_intruder' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_merit' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_nebula' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_oceanic' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_peren' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_premier' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_primo' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_regina' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_romero' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_sentinel' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_solair' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_stafford' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_stretch' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_sunrise' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_vincent' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_washing' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_willard' ] = { level = 3, delay = 5, max = 15 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_alpha' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_banshee' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_buffalo' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_bullet' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_cheetah' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_comet' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_euros' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_hotknife' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_infernus' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_phoenix' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_supergt' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_turismo' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_windsor' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_zr350' ] = { level = 5, delay = 5, max = 15 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_artict1' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_artict2a' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_artict2' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_artict3' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_petrotr' ] = { level = 3, delay = 5, max = 15 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_elegy' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_flash' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_jester' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_stratum' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_sultan' ] = { level = 5, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_uranus' ] = { level = 5, delay = 5, max = 15 },

    ----------------------------------------------------------------------------
    [ 'simfphys_gta_sa_topfun' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_burrito' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_hotdog' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_moonbeam' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_mrwhoop' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_newsvan' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_pony' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_rumpo' ] = { level = 3, delay = 5, max = 15 },
    [ 'simfphys_gta_sa_securica' ] = { level = 3, delay = 5, max = 15 },

    ----------------------------------------------------------------------------
    [ 'sim_fphys_pwavia' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwgaz52' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwhatchback' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwliaz' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwmoskvich' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwtrabant' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwtrabant02' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwvan' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwvolga' ] = { level = 2, delay = 10, max = 15 },
    [ 'sim_fphys_pwzaz' ] = { level = 2, delay = 10, max = 15 },

    ----------------------------------------------------------------------------
    [ 'sim_fphys_jeep' ] = { level = 3, delay = 10, max = 15 },
    [ 'sim_fphys_v8elite' ] = { level = 3, delay = 10, max = 15 },
    [ 'sim_fphys_van' ] = { level = 3, delay = 10, max = 15 },

    ----------------------------------------------------------------------------
    [ 'sim_fphys_hlalyxniva' ] = { level = 3, delay = 10, max = 15 },

    ----------------------------------------------------------------------------
    [ 'kmz' ] = { level = 3, delay = 10, max = 15 },
    [ 'kmz_orange' ] = { level = 3, delay = 10, max = 15 },
    [ 'kmz_red' ] = { level = 3, delay = 10, max = 15 },
    [ 'kmz_yellow' ] = { level = 3, delay = 10, max = 15 },

    ----------------------------------------------------------------------------
    [ 'sim_fphys_Dolly' ] = { level = 3, delay = 10, max = 15 },
    [ 'sim_fphys_Trailer' ] = { level = 3, delay = 10, max = 15 },

    ----------------------------------------------------------------------------
    [ 'simfphys_btr80' ] = { level = 4, delay = 10, max = 15 },
    [ 'simfphys_btr80a' ] = { level = 4, delay = 10, max = 15 },

    ----------------------------------------------------------------------------
    [ 'sw_dieselv2_new' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_dieselv2_bogie' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_bogie' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_box_long' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_box_short' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_car_long' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_car_short' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_cargo_long' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_cargo_short' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_flat_long' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_flat_short' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_pass_long' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_pass_short' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_tank_long' ] = { level = 10, delay = 1, max = 4 },
    [ 'sw_wagon_tank_short' ] = { level = 10, delay = 1, max = 4 },
}