Ambi.Rus.restrict_items[ 'Tools' ] = {
    [ 'wire_button' ] = { level = 3 },
    [ 'wire_gates' ] = { level = 3 },
    [ 'wire_lamp' ] = { level = 3 },
    [ 'wire_light' ] = { level = 3 },
    [ 'wire_latch' ] = { level = 3 },
    [ 'wire_nailer' ] = { level = 3 },
    [ 'wire_hydraulic' ] = { level = 3 },
    [ 'wire_grabber' ] = { level = 3 },
    [ 'wire_freezer' ] = { level = 3 },
    [ 'wire_thruster' ] = { level = 3 },
    [ 'wire_hoverball' ] = { level = 3 },
    [ 'wire_forcer' ] = { level = 3 },
    [ 'wire_detonator' ] = { level = 20 },
    [ 'wire_simple_explosive' ] = { level = 20 },
    [ 'wire_explosive' ] = { level = 20 },
    
    -------------------------------------------------------------------------------
    [ 'wire_expression2' ] = { level = 3, access = 1 },
    [ 'wire_egp' ] = { level = 4, access = 1 },
    [ 'starfall_processor' ] = { level = 12 },
    [ 'starfall_component' ] = { level = 12, access = 1 },
    [ 'wire_cpu' ] = { level = 32, access = 3 },
    [ 'wire_spu' ] = { level = 32, access = 3 },
    [ 'wire_gpu' ] = { level = 32, access = 3 },

    -------------------------------------------------------------------------------
    [ 'smartweld' ] = { level = 4 },
    [ 'axis' ] = { level = 5 },
    [ 'ballsocket' ] = { level = 5 },
    [ 'ballsocket_adv' ] = { level = 5 },
    [ 'elastic' ] = { level = 5 },
    [ 'hydraulic' ] = { level = 5 },
    [ 'multi_parent' ] = { level = 4 },
    [ 'multi_unparent' ] = { level = 4 },
    [ 'muscle' ] = { level = 5 },
    [ 'pulley' ] = { level = 5 },
    [ 'rope' ] = { level = 5 },
    [ 'slider' ] = { level = 5 },
    [ 'weld' ] = { level = 5 },
    [ 'winch' ] = { level = 5 },
    [ 'wheel' ] = { level = 5 },
    [ 'paint' ] = { level = 2 },

    -------------------------------------------------------------------------------
    [ 'advdupe2' ] = { level = 3 },
    [ 'stacker_improved' ] = { level = 1 },
    [ 'button' ] = { level = 3 },
    [ 'fading_door' ] = { level = 2 },
    [ 'keypad_willox' ] = { level = 2 },
    [ 'keypad_willox_wire' ] = { level = 2 },
    [ 'balloon' ] = { level = 5 },
    [ 'rt_buoyancy' ] = { level = 5 },
    [ 'fin2' ] = { level = 6 },
    [ 'hoverball' ] = { level = 6 },
    [ 'weight' ] = { level = 6 },
    [ 'wheel' ] = { level = 6 },
    [ 'textscreen' ] = { level = 2 },
    [ 'thruster' ] = { level = 3 },
    [ 'adv_mass' ] = { level = 10 },
    [ 'nocollide' ] = { level = 3 },
    [ 'physprop' ] = { level = 25 },
    [ 'gmod_tool_ttc' ] = { level = 10 },
    [ 'trackassembly' ] = { level = 10 },

    -------------------------------------------------------------------------------
    [ 'eyeposer' ] = { level = 3 },
    [ 'faceposer' ] = { level = 3 },
    [ 'finger' ] = { level = 3 },
    [ 'inflator' ] = { level = 3 },
    [ 'ragdollstand' ] = { level = 3 },

    -------------------------------------------------------------------------------
    [ 'camera' ] = { level = 1 },
    [ 'color' ] = { level = 2 },
    [ 'material' ] = { level = 2 },
    [ 'submaterial' ] = { level = 3, build = 100 },
    [ 'advmat' ] = { level = 3, build = 200 },
    [ 'rtcam' ] = { level = 4, build = 250 },
    [ 'trails' ] = { level = 5, build = 300 },

    -------------------------------------------------------------------------------
    [ 'npctool_controller' ] = { level = 25, admin = true },
    [ 'npctool_follower' ] = { level = 25, admin = true },
    [ 'npctool_health' ] = { level = 25, admin = true },
    [ 'npctool_notarget' ] = { level = 25, admin = true },
    [ 'npctool_proficiency' ] = { level = 25, admin = true },
    [ 'npctool_relationships' ] = { level = 25, admin = true },
    [ 'npctool_newroute' ] = { level = 25, admin = true },
    [ 'npctool_viewcam' ] = { level = 25, admin = true },
    [ 'npctool_spawner' ] = { level = 50, admin = true },
    [ 'npctool_newspawner' ] = { level = 55, admin = true },

    -------------------------------------------------------------------------------
    [ 'dv_route' ] = { level = 25 },
    [ 'simfphysduplicator' ] = { level = 10 },
    [ 'simfphyswheeleditor' ] = { level = 12 },
    [ 'simfphys_lighting_color' ] = { level = 4 },
    [ 'simfphyssoundeditor' ] = { level = 4 },
    [ 'simfphysmiscsoundeditor' ] = { level = 4 },
    [ 'simfphyssuspensioneditor' ] = { level = 4 },
    [ 'simfphysgeareditor' ] = { level = 4 },
    [ 'simfphyseditor' ] = { level = 4 },

    -------------------------------------------------------------------------------
    [ 'rb655_easy_animation' ] = { level = 3, admin = true },
    [ 'rb655_easy_bonemerge' ] = { level = 3, admin = true },
    [ 'hoverboard' ] = { level = 2 },

    -------------------------------------------------------------------------------
    [ 'vjstool_bullseye' ] = { level = 5, admin = true },
    [ 'vjstool_healthmodifier' ] = { level = 5, admin = true },
    [ 'vjstool_npcrelationship' ] = { level = 5, admin = true },
    [ 'vjstool_notarget' ] = { level = 5, admin = true },
    [ 'vjstool_entityscanner' ] = { level = 5, admin = true },
    [ 'vjstool_npcequipment' ] = { level = 5, admin = true },
    [ 'vjstool_npcspawner' ] = { level = 5, admin = true },
    [ 'vjstool_npcmover' ] = { level = 5, admin = true },

    -------------------------------------------------------------------------------
    [ 'duplicator' ] = { level = 5, admin = true },
    [ 'dynamite' ] = { level = 5, admin = true },
}