game.AddDecal( "AlienBloodStain", "decals/bloodstain_201" )
game.AddDecal( "BloodStain", "decals/bloodstain_001" )
game.AddDecal( "BloodStain2", "decals/bloodstain_002" )
game.AddDecal( "BloodStain3", "decals/bloodstain_003" )
game.AddDecal( "BloodStain3b", "decals/bloodstain_003b" )
game.AddDecal( "BloodStain101", "decals/bloodstain_101" )
game.AddDecal( "BloodStain201", "decals/bloodstain_201" )
--game.AddDecal( "BloodStain201m", "decals/bloodstain_201m" )
game.AddDecal( "BornGraffitti", "decals/decalgraffiti024a" )
game.AddDecal( "BreenPoster", "decals/decal_posterbreen" )
game.AddDecal( "CarGraffitti", "decals/decalgraffiti006a" )
game.AddDecal( "CMBSign", "decals/decalsignpainted001a" )
game.AddDecal( "CMBSign2", "decals/decalsignpainted001b" )
game.AddDecal( "ConcreteDebris", "decals/debris_concrete001a" )
game.AddDecal( "ConcreteDebris2", "decals/debris_concrete001b" )
game.AddDecal( "Crater", "decals/decal_crater001a" )
game.AddDecal( "DangerFlammable", "decals/decalsigndanger001d" )
game.AddDecal( "DangerAuthorized", "decals/decalsigndanger001e" )
game.AddDecal( "DangerExplosives", "decals/decalsigndanger001f" )
game.AddDecal( "DawnGraffitti", "decals/decalgraffiti012a" )
game.AddDecal( "DecompPuddle", "decals/decomp_puddle1" )
game.AddDecal( "EvolutionGraffitti", "decals/decalgraffiti056a" )
game.AddDecal( "Extinguish1", "decals/extinguish1" )
game.AddDecal( "Extinguish2", "decals/extinguish2" )
game.AddDecal( "Graffitti001a", "decals/decalgraffiti001a" )
game.AddDecal( "Graffitti001b", "decals/decalgraffiti001b" )
game.AddDecal( "Graffitti001c", "decals/decalgraffiti001c" )
game.AddDecal( "Graffitti001d", "decals/decalgraffiti001d" )
game.AddDecal( "Graffitti005a", "decals/decalgraffiti005a" )
game.AddDecal( "Graffitti007a", "decals/decalgraffiti007a" )
game.AddDecal( "Graffitti008a", "decals/decalgraffiti008a" )
game.AddDecal( "Graffitti009a", "decals/decalgraffiti009a" )
game.AddDecal( "Graffitti010a", "decals/decalgraffiti010a" )
game.AddDecal( "Graffitti011a", "decals/decalgraffiti011a" )
game.AddDecal( "Ivy01", "decals/ivy01" )
game.AddDecal( "Ivy02", "decals/ivy02" )
game.AddDecal( "Ivy03", "decals/ivy03" )
game.AddDecal( "Lambda", "decals/lambdaspray_1a" )
game.AddDecal( "Lambda2", "decals/lambdaspray_2a" )
game.AddDecal( "Leaves", "decals/leaves_ground01" )
game.AddDecal( "Leaves2", "decals/leaves_ground02" )
game.AddDecal( "OrangesLemonsGraffitti", "decals/decalgraffiti062a" )
game.AddDecal( "PoliceGraffitti", "decals/decalgraffiti059a" )
game.AddDecal( "PoliceLine", "decals/decal_policeline01a" )
game.AddDecal( "Posters001", "decals/decal_posters001a" )
game.AddDecal( "Posters002", "decals/decal_posters002a" )
game.AddDecal( "Posters003", "decals/decal_posters003a" )
game.AddDecal( "Posters005", "decals/decal_posters005a" )
game.AddDecal( "Posters006", "decals/decal_posters006a" )
game.AddDecal( "PowerOutlet", "decals/decalpoweroutlet001a" )
game.AddDecal( "ResistGraffitti", "decals/decalgraffiti003a" )
game.AddDecal( "Rubble01a", "decals/rubble01a" )
game.AddDecal( "Rug001", "decals/decalrug001a" )
--game.AddDecal( "Rug001a", "overlays/rug001a" )
game.AddDecal( "Rug002", "decals/decalrug002a" )
game.AddDecal( "Rug003", "decals/decalrug003a" )
game.AddDecal( "Rug004", "decals/decalrug004a" )
game.AddDecal( "Rug005", "decals/decalrug005a" )
game.AddDecal( "Snow1b", "decals/ship_snow1b" )
game.AddDecal( "TileDebris", "decals/debris_tile001a" )
game.AddDecal( "TireMarks", "decals/decaltiremark001a" )
game.AddDecal( "Trash01", "decals/trashdecal01a" )
game.AddDecal( "Trash02", "decals/trashdecal02a" )
game.AddDecal( "Trash03", "decals/trashdecal03a" )
game.AddDecal( "Trash04", "decals/trashdecal04a" )
game.AddDecal( "Trash05", "decals/trashdecal05a" )
game.AddDecal( "Unburrow", "decals/unburrow" )

list.Add( "PaintMaterials", "AlienBloodStain" )
list.Add( "PaintMaterials", "BloodStain" )
list.Add( "PaintMaterials", "BloodStain2" )
list.Add( "PaintMaterials", "BloodStain3" )
list.Add( "PaintMaterials", "BloodStain3b" )
list.Add( "PaintMaterials", "BloodStain101" )
list.Add( "PaintMaterials", "BloodStain201" )
--list.Add( "PaintMaterials", "BloodStain201m" )
list.Add( "PaintMaterials", "BornGraffitti" )
list.Add( "PaintMaterials", "BreenPoster" )
list.Add( "PaintMaterials", "CarGraffitti" )
list.Add( "PaintMaterials", "CMBSign" )
list.Add( "PaintMaterials", "CMBSign2" )
list.Add( "PaintMaterials", "ConcreteDebris" )
list.Add( "PaintMaterials", "ConcreteDebris2" )
list.Add( "PaintMaterials", "Crater" )
list.Add( "PaintMaterials", "DangerFlammable" )
list.Add( "PaintMaterials", "DangerAuthorized" )
list.Add( "PaintMaterials", "DangerExplosives" )
list.Add( "PaintMaterials", "DawnGraffitti" )
list.Add( "PaintMaterials", "DecompPuddle" )
list.Add( "PaintMaterials", "Extinguish1" )
list.Add( "PaintMaterials", "Extinguish2" )
list.Add( "PaintMaterials", "EvolutionGraffitti" )
list.Add( "PaintMaterials", "Graffitti001a" )
list.Add( "PaintMaterials", "Graffitti001b" )
list.Add( "PaintMaterials", "Graffitti001c" )
list.Add( "PaintMaterials", "Graffitti001d" )
list.Add( "PaintMaterials", "Graffitti005a" )
list.Add( "PaintMaterials", "Graffitti006a" )
list.Add( "PaintMaterials", "Graffitti007a" )
list.Add( "PaintMaterials", "Graffitti008a" )
list.Add( "PaintMaterials", "Graffitti009a" )
list.Add( "PaintMaterials", "Graffitti010a" )
list.Add( "PaintMaterials", "Graffitti011a" )
list.Add( "PaintMaterials", "Ivy01" )
list.Add( "PaintMaterials", "Ivy02" )
list.Add( "PaintMaterials", "Ivy03" )
list.Add( "PaintMaterials", "Lambda" )
list.Add( "PaintMaterials", "Lambda2" )
list.Add( "PaintMaterials", "Leaves" )
list.Add( "PaintMaterials", "Leaves2" )
list.Add( "PaintMaterials", "OrangesLemonsGraffitti" )
list.Add( "PaintMaterials", "PoliceGraffitti" )
list.Add( "PaintMaterials", "PoliceLine" )
list.Add( "PaintMaterials", "Posters001" )
list.Add( "PaintMaterials", "Posters002" )
list.Add( "PaintMaterials", "Posters003" )
list.Add( "PaintMaterials", "Posters005" )
list.Add( "PaintMaterials", "Posters006" )
list.Add( "PaintMaterials", "PowerOutlet" )
list.Add( "PaintMaterials", "ResistGraffitti" )
list.Add( "PaintMaterials", "Rubble01a" )
list.Add( "PaintMaterials", "Rug001" )

--bad scaling
--list.Add( "PaintMaterials", "Rug001a" )

list.Add( "PaintMaterials", "Rug002" )
list.Add( "PaintMaterials", "Rug003" )
list.Add( "PaintMaterials", "Rug004" )
list.Add( "PaintMaterials", "Rug005" )
list.Add( "PaintMaterials", "Snow1b" )
list.Add( "PaintMaterials", "TileDebris" )
list.Add( "PaintMaterials", "TireMarks" )
list.Add( "PaintMaterials", "Trash01" )
list.Add( "PaintMaterials", "Trash02" )
list.Add( "PaintMaterials", "Trash03" )
list.Add( "PaintMaterials", "Trash04" )
list.Add( "PaintMaterials", "Trash05" )
list.Add( "PaintMaterials", "Unburrow" )

if IsMounted("hl2mp") then

game.AddDecal( "Spray Canned", "vgui/logos/spray_canned" )
game.AddDecal( "Spray Combine", "vgui/logos/spray_combine" )
game.AddDecal( "Spray Cop", "vgui/logos/spray_cop" )
game.AddDecal( "Spray D0G", "vgui/logos/spray_dog" )
game.AddDecal( "Spray Freeman", "vgui/logos/spray_freeman" )
game.AddDecal( "Spray Head", "vgui/logos/spray_head" )
game.AddDecal( "Spray Lambda", "vgui/logos/spray_lambda" )
game.AddDecal( "Spray Plumbed", "vgui/logos/spray_plumbed" )
game.AddDecal( "Spray Soldier", "vgui/logos/spray_soldier" )

list.Add( "PaintMaterials", "Spray Canned" )
list.Add( "PaintMaterials", "Spray Combine" )
list.Add( "PaintMaterials", "Spray Cop" )
list.Add( "PaintMaterials", "Spray D0G" )
list.Add( "PaintMaterials", "Spray Freeman" )
list.Add( "PaintMaterials", "Spray Head" )
list.Add( "PaintMaterials", "Spray Lambda" )
list.Add( "PaintMaterials", "Spray Plumbed" )
list.Add( "PaintMaterials", "Spray Soldier" )
end

if IsMounted("ep2") then

game.AddDecal( "AntlionBloodStain", "overlays/antlion_bloodstain_002" )
--too big -- need to make new vmt for proper scaling
--game.AddDecal( "BloodpoolEP2_1", "overlays/bloodpool1" )
--game.AddDecal( "BloodpoolEP2_2", "overlays/bloodpool2" )
--game.AddDecal( "BloodpoolEP2_3", "overlays/bloodpool3" )
--game.AddDecal( "BloodpoolEP2_4", "overlays/bloodpool4" )
game.AddDecal( "BootPrints01", "overlays/bootprint_01" )
game.AddDecal( "BootPrints02", "overlays/bootprint_02" )
game.AddDecal( "GraffitiEP2_1", "overlays/ep2_graffiti01" )
game.AddDecal( "GraffitiEP2_2", "overlays/ep2_graffiti02" )
game.AddDecal( "GraffitiEP2_3", "overlays/ep2_graffiti03" )
--game.AddDecal( "WhiteForestLogo", "overlays/whiteforestlogo" )

list.Add( "PaintMaterials", "AntlionBloodStain" )
--list.Add( "PaintMaterials", "BloodpoolEP2_1" )
--list.Add( "PaintMaterials", "BloodpoolEP2_2" )
--list.Add( "PaintMaterials", "BloodpoolEP2_3" )
--list.Add( "PaintMaterials", "BloodpoolEP2_4" )
list.Add( "PaintMaterials", "BootPrints01" )
list.Add( "PaintMaterials", "BootPrints02" )
list.Add( "PaintMaterials", "GraffitiEP2_1" )
list.Add( "PaintMaterials", "GraffitiEP2_2" )
list.Add( "PaintMaterials", "GraffitiEP2_3" )
--list.Add( "PaintMaterials", "WhiteForestLogo" )
end

if IsMounted("cstrike") then

game.AddDecal( "A", "decals/sitea" )
game.AddDecal( "ArrowLeft", "decals/arrow_left" )
game.AddDecal( "ArrowRight", "decals/arrow_right" )
game.AddDecal( "ArrowUpLeft", "decals/arrowuplf" )
game.AddDecal( "ArrowUpRight", "decals/arrowuprt" )
game.AddDecal( "B", "decals/siteb" )
game.AddDecal( "CheFace", "decals/face01" )
game.AddDecal( "DustFlag", "decals/dustflag" )
game.AddDecal( "DustGraffiti01", "decals/graffiti01" )
game.AddDecal( "DustGraffiti02", "decals/graffiti02" )
game.AddDecal( "DustGraffiti03", "decals/graffiti03" )
game.AddDecal( "Hay", "decals/infhay" )
game.AddDecal( "HostagePoint", "decals/hrpoint" )
game.AddDecal( "HostagePoint_Militia", "decals/militiahostagerescue" )
game.AddDecal( "ItalyFlag", "decals/italy_flag" )
game.AddDecal( "Leaves_Militia", "decals/milleaves" )
game.AddDecal( "OfficeSlideshow", "decals/slide" )
--game.AddDecal( "Posters_CS_01", "decals/posters01" )
--game.AddDecal( "Posters_CS_02", "decals/posters02" )
--game.AddDecal( "Posters_CS_03", "decals/posters03" )
--game.AddDecal( "Posters_CS_04", "decals/posters04" )
--game.AddDecal( "Posters_CS_05", "decals/posters05" )
game.AddDecal( "RedCarpet", "decals/tides_redcarpet" )
game.AddDecal( "Sand", "decals/sanddecal01" )
game.AddDecal( "Sand2", "decals/sanddecal02" )
game.AddDecal( "Sand3", "decals/sanddecal03" )
game.AddDecal( "Snow", "decals/snow01" )
game.AddDecal( "Target", "decals/target" )

game.AddDecal( "Spray Bullseye", "vgui/logos/spray_bullseye" )
game.AddDecal( "Spray Crosshairs", "vgui/logos/spray_crosshairs" )
game.AddDecal( "Spray Crybaby", "vgui/logos/spray_crybaby" )
game.AddDecal( "Spray Elited", "vgui/logos/spray_elited" )
game.AddDecal( "Spray Flashbanged", "vgui/logos/spray_flashbanged" )
game.AddDecal( "Spray Grenaded", "vgui/logos/spray_grenaded" )
game.AddDecal( "Spray Headshot", "vgui/logos/spray_headshot" )
game.AddDecal( "Spray Insights", "vgui/logos/spray_insights" )
game.AddDecal( "Spray Kamikazi", "vgui/logos/spray_kamikazi" )
game.AddDecal( "Spray Kilroy", "vgui/logos/spray_kilroy" )
game.AddDecal( "Spray Knifed", "vgui/logos/spray_knifed" )
game.AddDecal( "Spray Nobombs", "vgui/logos/spray_nobombs" )
game.AddDecal( "Spray Nosmoking", "vgui/logos/spray_nosmoking" )
game.AddDecal( "Spray Nowar", "vgui/logos/spray_nowar" )
game.AddDecal( "Spray Touchdown", "vgui/logos/spray_touchdown" )

list.Add( "PaintMaterials", "A" )
list.Add( "PaintMaterials", "ArrowLeft" )
list.Add( "PaintMaterials", "ArrowRight" )
list.Add( "PaintMaterials", "ArrowUpLeft" )
list.Add( "PaintMaterials", "ArrowUpRight" )
list.Add( "PaintMaterials", "B" )
list.Add( "PaintMaterials", "CheFace" )
list.Add( "PaintMaterials", "DustFlag" )
list.Add( "PaintMaterials", "DustGraffiti01" )
list.Add( "PaintMaterials", "DustGraffiti02" )
list.Add( "PaintMaterials", "DustGraffiti03" )
list.Add( "PaintMaterials", "Hay" )
list.Add( "PaintMaterials", "HostagePoint" )
list.Add( "PaintMaterials", "HostagePoint_Militia" )
list.Add( "PaintMaterials", "ItalyFlag" )
list.Add( "PaintMaterials", "Leaves_Militia" )
list.Add( "PaintMaterials", "OfficeSlideshow" )

--bad scaling
--list.Add( "PaintMaterials", "Posters_CS_01" )
--list.Add( "PaintMaterials", "Posters_CS_02" )
--list.Add( "PaintMaterials", "Posters_CS_03" )
--list.Add( "PaintMaterials", "Posters_CS_04" )
--list.Add( "PaintMaterials", "Posters_CS_05" )

list.Add( "PaintMaterials", "RedCarpet" )
list.Add( "PaintMaterials", "Sand" )
list.Add( "PaintMaterials", "Sand2" )
list.Add( "PaintMaterials", "Sand3" )
list.Add( "PaintMaterials", "Snow" )
list.Add( "PaintMaterials", "Target" )

list.Add( "PaintMaterials", "Spray Bullseye" )
list.Add( "PaintMaterials", "Spray Crosshairs" )
list.Add( "PaintMaterials", "Spray Crybaby" )
list.Add( "PaintMaterials", "Spray Elited" )
list.Add( "PaintMaterials", "Spray Flashbanged" )
list.Add( "PaintMaterials", "Spray Grenaded" )
list.Add( "PaintMaterials", "Spray Headshot" )
list.Add( "PaintMaterials", "Spray Insights" )
list.Add( "PaintMaterials", "Spray Kamikazi" )
list.Add( "PaintMaterials", "Spray Kilroy" )
list.Add( "PaintMaterials", "Spray Knifed" )
list.Add( "PaintMaterials", "Spray Nobombs" )
list.Add( "PaintMaterials", "Spray Nosmoking" )
list.Add( "PaintMaterials", "Spray Nowar" )
list.Add( "PaintMaterials", "Spray Touchdown" )
end

if IsMounted("dod") then

game.AddDecal( "FrenchPoster", "decals/fr_poster01" )
game.AddDecal( "ItalianPoster03", "decals/it_poster003" )
game.AddDecal( "ItalianPoster04", "decals/it_poster004" )
game.AddDecal( "ItalianPoster06", "decals/it_poster006" )
game.AddDecal( "ItalianPoster10", "decals/it_poster010" )
game.AddDecal( "ItalianMural", "decals/italianmural" )
game.AddDecal( "Leaves03", "decals/leaves_ground03" )
game.AddDecal( "Maps_DOD_01", "decals/mapdecal01" )
game.AddDecal( "Maps_DOD_02", "decals/mapdecal02" )
game.AddDecal( "Muddy", "decals/muddydecal001" )
game.AddDecal( "Rubble001", "decals/rubbledecal001" )
game.AddDecal( "Shells", "decals/shelldebris" )
game.AddDecal( "Trash01b", "decals/trashdecal01b" )
--game.AddDecal( "TreeRoots", "decals/treeroots" )

list.Add( "PaintMaterials", "FrenchPoster" )
list.Add( "PaintMaterials", "ItalianPoster03" )
list.Add( "PaintMaterials", "ItalianPoster04" )
list.Add( "PaintMaterials", "ItalianPoster06" )
list.Add( "PaintMaterials", "ItalianPoster10" )
list.Add( "PaintMaterials", "ItalianMural" )
list.Add( "PaintMaterials", "Leaves03" )
list.Add( "PaintMaterials", "Maps_DOD_01" )
list.Add( "PaintMaterials", "Maps_DOD_02" )
list.Add( "PaintMaterials", "Muddy" )
list.Add( "PaintMaterials", "Rubble001" )
list.Add( "PaintMaterials", "Shells" )
list.Add( "PaintMaterials", "Trash01b" )
--list.Add( "PaintMaterials", "TreeRoots" )
end

-- none of these work right...
--[[
if IsMounted("portal") then

game.AddDecal( "ApertureLogoWorn", "signage/overlay_aperture_logo_worn" )
game.AddDecal( "CakeSign", "signage/signage_overlay_cake" )
game.AddDecal( "CompanionCubeSign", "signage/signage_overlay_companioncube" )
game.AddDecal( "EnergyBallSign", "signage/signage_overlay_energyball" )
game.AddDecal( "IncineratorSign", "signage/signage_overlay_incinerator" )
game.AddDecal( "ToxicSign", "signage/signage_overlay_toxic" )
game.AddDecal( "TurretSign", "signage/signage_overlay_turret" )

list.Add( "PaintMaterials", "ApertureLogoWorn" )
list.Add( "PaintMaterials", "CakeSign" )
list.Add( "PaintMaterials", "CompanionCubeSign" )
list.Add( "PaintMaterials", "EnergyBallSign" )
list.Add( "PaintMaterials", "IncineratorSign" )
list.Add( "PaintMaterials", "ToxicSign" )
list.Add( "PaintMaterials", "TurretSign" )
end
--]]

if IsMounted("tf") then

game.AddDecal( "ArrowDownBlue", "signs/arrow_dn_blue" )
game.AddDecal( "ArrowDownRed", "signs/arrow_dn_red" )
--game.AddDecal( "BarSign", "signs/sign_bar" )
--game.AddDecal( "BLULogo", "overlays/logo_blue" )
--game.AddDecal( "JudgementShedSign", "signs/sign_judge" )
--game.AddDecal( "MannCoLogo", "overlays/mann_co_logo_001" )
--game.AddDecal( "MannMiningSign", "signs/sign_mannmining" )
--game.AddDecal( "REDLogo", "overlays/logo_red" )
game.AddDecal( "TF2Blood1", "decals/blood1_tf2" )
game.AddDecal( "TF2Blood2", "decals/blood2_tf2" )
game.AddDecal( "TF2Blood3", "decals/blood3_tf2" )
game.AddDecal( "TF2Blood4", "decals/blood4_tf2" )
game.AddDecal( "TF2Blood5", "decals/blood5_tf2" )
game.AddDecal( "TF2Blood6", "decals/blood6_tf2" )
--game.AddDecal( "YetiMural", "overlays/saxton_yeti_mural" )

list.Add( "PaintMaterials", "ArrowDownBlue" )
list.Add( "PaintMaterials", "ArrowDownRed" )
--list.Add( "PaintMaterials", "BarSign" )
--list.Add( "PaintMaterials", "BLULogo" )
--list.Add( "PaintMaterials", "JudgementShedSign" )
--list.Add( "PaintMaterials", "MannCoLogo" )
--list.Add( "PaintMaterials", "MannMiningSign" )
--list.Add( "PaintMaterials", "REDLogo" )
list.Add( "PaintMaterials", "TF2Blood1" )
list.Add( "PaintMaterials", "TF2Blood2" )
list.Add( "PaintMaterials", "TF2Blood3" )
list.Add( "PaintMaterials", "TF2Blood4" )
list.Add( "PaintMaterials", "TF2Blood5" )
list.Add( "PaintMaterials", "TF2Blood6" )
--list.Add( "PaintMaterials", "YetiMural" )
end


if IsMounted("left4dead") then

game.AddDecal( "BloodSplatter", "decals/blood_splatter" )
game.AddDecal( "BloodSplatter2", "decals/blood_splatter2" )
game.AddDecal( "BloodStainHand", "decals/bloodstain_hand" )
game.AddDecal( "Blueprints", "decals/blueprints01" )
game.AddDecal( "DangerGraffiti", "decals/graffiti_danger" )
game.AddDecal( "GodIsDeadGraffiti", "decals/graffiti_goddead" )
game.AddDecal( "FarmMap", "decals/map_farm" )
game.AddDecal( "FoodGraffiti", "decals/graffiti_helpfood" )
game.AddDecal( "LootersGraffiti", "decals/graffiti_lootersshot" )
game.AddDecal( "Message01", "decals/message01" ) 
game.AddDecal( "Message02", "decals/message02" )
game.AddDecal( "Message03", "decals/message03" )
game.AddDecal( "Message04", "decals/message04" )
game.AddDecal( "Message05", "decals/message05" )
game.AddDecal( "MissingPosters", "decals/missing_posters_04" )
game.AddDecal( "PlayingCards", "decals/cards_playing00" )
game.AddDecal( "PumpNRunSign", "decals/pump_n_run" )
game.AddDecal( "ShadowRuralTree", "decals/shadow_rural_tree00" )
game.AddDecal( "ShadowSimple", "decals/shadow_simple" )

list.Add( "PaintMaterials", "BloodSplatter" )
list.Add( "PaintMaterials", "BloodSplatter2" )
list.Add( "PaintMaterials", "BloodStainHand" )
list.Add( "PaintMaterials", "Blueprints" )
list.Add( "PaintMaterials", "DangerGraffiti" )
list.Add( "PaintMaterials", "GodIsDeadGraffiti" )
list.Add( "PaintMaterials", "FarmMap" )
list.Add( "PaintMaterials", "FoodGraffiti" )
list.Add( "PaintMaterials", "LootersGraffiti" )
list.Add( "PaintMaterials", "Message01" )
list.Add( "PaintMaterials", "Message02" )
list.Add( "PaintMaterials", "Message03" )
list.Add( "PaintMaterials", "Message04" )
list.Add( "PaintMaterials", "Message05" )
list.Add( "PaintMaterials", "MissingPosters" )
list.Add( "PaintMaterials", "PlayingCards" )
list.Add( "PaintMaterials", "PumpNRunSign" )
list.Add( "PaintMaterials", "ShadowSimple" )
list.Add( "PaintMaterials", "ShadowRuralTree" )
end


if IsMounted("left4dead2") then
game.AddDecal( "ShadowSimple2", "decals/simpleshadow" )
game.AddDecal( "SwampLeaves", "decals/swampleaves_decal01" )
game.AddDecal( "TallyMarks01", "decals/days01" )
game.AddDecal( "TallyMarks02", "decals/days02" )
game.AddDecal( "TallyMarks03", "decals/days03" )

list.Add( "PaintMaterials2", "ShadowSimple" )
list.Add( "PaintMaterials", "SwampLeaves" )
list.Add( "PaintMaterials", "TallyMarks01" )
list.Add( "PaintMaterials", "TallyMarks02" )
list.Add( "PaintMaterials", "TallyMarks03" )
end


AddCSLuaFile()